package au.com.illyrian.classmaker.types;

import au.com.illyrian.classmaker.ClassMaker;

public class MakerClassType extends ClassType
{
    private final ClassMaker classMaker;
    /**
     * Constructor for a <code>ClassType</code> generated by a ClassMaker instance.
     * @param className the name of the class
     */
    public MakerClassType(ClassMaker classMaker)
    {
        super(classMaker.getFullyQualifiedClassName());
        this.classMaker = classMaker;
    }

    public ClassMaker getClassMaker() {
        return classMaker;
    }
}
