{
name  ::= IDENTIFIER  { ast.Name($1) } ;
        
import_path_plus ::= name DOT import_path_plus   { ast.Dot($1, $3) }
                 |   name SEMI                   { $1 }
                 |   name DOTSTAR SEMI           { ast.Dot($1, ast.Name("*")) }
                 |   MULT SEMI                   { ast.Name("*") }
                 |   error("Incomplete import path") ;

import_mult:AstStructure
                 ::= IMPORT import_path_plus import_mult  { ast.Seq(ast.Import($2), $3) }
                 |   IMPORT import_path_plus              { ast.Import($2) } 
                 ;
                 
import_opt:AstStructure
                 ::= import_mult
                 |   /*EMPTY*/ ;

goal:AstStructure ::= import_opt { ast.Module(null, $1, null) } ;
}